# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JJPlayerView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JJPlayerView
  
pod 'Masonry', '~> 1.1.0'
pod 'YYCategories', '~> 1.0.4'


end
